language: php

php:
    - 5.3

env:
    - DB=MYSQL CORE_RELEASE=2.4

matrix:
  include:
    - php: 5.3
      env: DB=PGSQL CORE_RELEASE=2.4
    - php: 5.4
      env: DB=SQLITE CORE_RELEASE=2.4
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=2.4  

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script: 
  - phpunit suspendspammer/tests/*